// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using R54_M11_Class_06_Work_02.Models;

#nullable disable

namespace R54_M11_Class_06_Work_01.Migrations.ProductDb
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("R54_M11_Class_06_Work_02.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<bool?>("OnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            OnSale = false,
                            Picture = "1.jpg",
                            Price = 1765m,
                            ProductName = "Product 1",
                            Size = 2
                        },
                        new
                        {
                            ProductId = 2,
                            OnSale = true,
                            Picture = "2.jpg",
                            Price = 1040m,
                            ProductName = "Product 2",
                            Size = 3
                        },
                        new
                        {
                            ProductId = 3,
                            OnSale = false,
                            Picture = "3.jpg",
                            Price = 1771m,
                            ProductName = "Product 3",
                            Size = 1
                        },
                        new
                        {
                            ProductId = 4,
                            OnSale = true,
                            Picture = "4.jpg",
                            Price = 1366m,
                            ProductName = "Product 4",
                            Size = 2
                        },
                        new
                        {
                            ProductId = 5,
                            OnSale = false,
                            Picture = "5.jpg",
                            Price = 1886m,
                            ProductName = "Product 5",
                            Size = 1
                        });
                });

            modelBuilder.Entity("R54_M11_Class_06_Work_02.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<DateTime?>("Date")
                        .IsRequired()
                        .HasColumnType("date");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int?>("Quantity")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("ProductId");

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            Date = new DateTime(2022, 9, 7, 17, 13, 39, 462, DateTimeKind.Local).AddTicks(367),
                            ProductId = 1,
                            Quantity = 147
                        },
                        new
                        {
                            SaleId = 2,
                            Date = new DateTime(2022, 6, 5, 17, 13, 39, 462, DateTimeKind.Local).AddTicks(400),
                            ProductId = 2,
                            Quantity = 105
                        },
                        new
                        {
                            SaleId = 3,
                            Date = new DateTime(2022, 8, 8, 17, 13, 39, 462, DateTimeKind.Local).AddTicks(408),
                            ProductId = 3,
                            Quantity = 139
                        },
                        new
                        {
                            SaleId = 4,
                            Date = new DateTime(2022, 8, 3, 17, 13, 39, 462, DateTimeKind.Local).AddTicks(415),
                            ProductId = 4,
                            Quantity = 142
                        },
                        new
                        {
                            SaleId = 5,
                            Date = new DateTime(2022, 7, 29, 17, 13, 39, 462, DateTimeKind.Local).AddTicks(422),
                            ProductId = 5,
                            Quantity = 110
                        },
                        new
                        {
                            SaleId = 6,
                            Date = new DateTime(2022, 7, 25, 17, 13, 39, 462, DateTimeKind.Local).AddTicks(431),
                            ProductId = 1,
                            Quantity = 191
                        },
                        new
                        {
                            SaleId = 7,
                            Date = new DateTime(2022, 8, 28, 17, 13, 39, 462, DateTimeKind.Local).AddTicks(481),
                            ProductId = 2,
                            Quantity = 159
                        },
                        new
                        {
                            SaleId = 8,
                            Date = new DateTime(2022, 6, 20, 17, 13, 39, 462, DateTimeKind.Local).AddTicks(491),
                            ProductId = 3,
                            Quantity = 102
                        });
                });

            modelBuilder.Entity("R54_M11_Class_06_Work_02.Models.Sale", b =>
                {
                    b.HasOne("R54_M11_Class_06_Work_02.Models.Product", "Product")
                        .WithMany("Sales")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("R54_M11_Class_06_Work_02.Models.Product", b =>
                {
                    b.Navigation("Sales");
                });
#pragma warning restore 612, 618
        }
    }
}
